LoginURL = "https://procapital.mohdfaiz.com/login.php"
IntradayURL = "https://procapital.mohdfaiz.com/intraday-calls.php"
UsernameXpath = """//*[@id="panel_dn"]/div[2]/form/div[1]/div/input"""
PasswordXpath = """//*[@id="panel_dn"]/div[2]/form/div[2]/div/input"""
LoginButtonXpath = """//*[@id="panel_dn"]/div[2]/form/div[3]/div/input"""
NotificationProposeXpath = """//*[@id="onesignal-popover-allow-button"]"""
CallTableRow="""//*[@id="responsecontainer"]/div/table/tbody/tr[1]/td[1]"""
Username = "rajatnagpure.rn@gmail.com"
Password = "Rajat@321"